version: '3.8'

services:
  word-memorizer:
    build: .
    container_name: word-memorizer
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_RUNTIME_PATH=${PULSE_RUNTIME_PATH}
      - PULSE_NATIVE=1
    volumes:
      # X11 socket for GUI display
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # 音频支持
      - /run/user/1000/pulse:/run/user/1000/pulse:ro
      # 数据持久化
      - ./data:/app/data
      # 缓存持久化  
      - word-memorizer-cache:/app/cache
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped
    
volumes:
  word-memorizer-cache: